---
ssh_port: 22
master: 54.208.117.154
server_ssh_key: "/Users/pivotal/.ssh/id_rsa"
recipes:
- pivotal_ci::jenkins
- pivotal_ci::limited_travis_ci_environment
- pivotal_ci
cookbook_paths:
- "./chef/cookbooks/"
- "./chef/travis-cookbooks/ci_environment"
- "./chef/project-cookbooks"
node_attributes:
  travis_build_environment:
    user: jenkins
    group: nogroup
    home: "/var/lib/jenkins"
  nginx:
    basic_auth_user: ci
    basic_auth_password: urkel9rat
  jenkins:
    builds:
    - name: ci_test
      repository: git@github.com:butzopower/ci_test.git
      branch: master
      command: "./ci_build.sh"
      junit_publisher: true
instance_size: c1.medium
github_ssh_key: "/Users/pivotal/.ssh/ci_test_deploy"
security_group: ciborg
availability_zone: us-east-1b
aws_key: AKIAIOM6FJVOHIT2NJVQ
aws_secret: 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
instance_id: i-6d218a4e
